package com.sqli.gdmr.Enums;

public enum TypesVisite {
    VISITE_SPONTANEE,
    VISITE_EMBAUCHE,
    VISITE_ANNUELLE,
    VISITE_SUITE_A_UNE_ABSENCE_PROLONGEE,
    VISITE_SUITE_A_UN_CONGE_DE_MATERNITE_OU_PROLONGATION,
    VISITE_SUITE_A_UN_ACCIDENT_DU_TRAVAIL_OU_DU_TRAJET
}
